### ISSUE TITLE
In CSS is het gebruikelijk om eerst de styling voor de meerderheid te zetten en dan uitzonderingen daarop te maken

### ISSUE THREAD

**Issue by JeroenHeemskerk** [tkivits/educom-webshop-basis#15]
Ik zie in de CSS staan
https://github.com/tkivits/educom-webshop-basis/blob/e2ffcd459ed6c8ae25f1b0e243074b3d31fb1826/CSS/stylesheet.css#L34
hier maak je voor een select aantal typen een specifieke styling, als ik dan een ander type toevoeg, heeft deze niet deze styling. 
Het is beter om bijv. alles 400px te maken en dan voor bijv. de button een uitzondering te maken
```css
.form input, .form textarea {
	width: 400px;
}
.form input[type='button'] {
	width: auto;
}
```
